### PR TITLE
Changed ValueSerializer to VertexiumSerializer to be more generic

### PR DESCRIPTION
**Pull request by joeferner**
Changed `ValueSerializer` to `VertexiumSerializer`. This requires a change to your configuration:
  `accumulo.graph.valueSerializer` is now `accumulo.graph.serializer` and the class name specified should change as well.

### CODE REVIEW

**Comment by kunklejr** [comment]
What's the purpose of the change? I imagine it's more than just a name change.

**Comment by joeferner** [comment]
I would like the future JDBC backend to also use it and currently the serializers are tied to Accumulo via the `Value` class

**Comment by kunklejr** [comment]
I see. Thanks for the context. That makes sense.

**Comment by srfarley** [comment]
Looks good!

**Pull request merged**
